### ISSUE TITLE
Plugin doesn't work with Rider 2024.3

### ISSUE THREAD

**Issue by keyz182** [Garethp/Rider-RimworldDevelopment#55]
Various method not found exceptions when run with all other plugins disabled. 

Project loading hangs at "Starting Resharper Engine"

[idea.log](https://github.com/user-attachments/files/17756944/idea.log)

Platform: Windows 11
Rider Version: 2024.3 / Build #RD-243.21565.191

**Comment by keyz182** [comment]
Had a go recompiling targetting 2024.3, but not that easy it seems. It appears that a few namespaces have either gone, or have moved, but I can't see where.

**Comment by LinnielDW** [comment]
Chiming in that this is again broken in 2025.1:

> Message = “Method not found: 'Void JetBrains.ProjectModel.ProjectsHost.Impl.SolutionMark..ctor(JetBrains.Util.VirtualFileSystemPath, System.Collections.Generic.IReadOnlyList`1<JetBrains.ProjectModel.ProjectsHost.Impl.ISolutionConfigurationDefaults>)'.”
StackTraceString = “
  at ReSharperPlugin.RimworldDev.RimworldXmlProject.Solution.RimworldSolutionMark..ctor(VirtualFileSystemPath aboutFile, VirtualFileSystemPath solutionFilePath, IReadOnlyList`1 solutionConfigurationDefaultsSet)
     at ReSharperPlugin.RimworldDev.RimworldXmlProject.Solution.RimworldSolutionMarkProvider.TryCreate(RdSolutionDescription solutionDescription) in C:\Users\Gareth\RiderProjects\Rider-RimworldDevelopment\src\dotnet\ReSharperPlugin.RimworldDev\RimworldXmlProject\Solution\RimworldSolutionMarkProvider.cs:line 57
     at JetBrains.Rider.Backend.Features.ProjectModel.RiderSolutionWatcher.CreateSolutionMark(RdSolutionDescription description) in CreateSolutionMark.il:line IL_0016 mvid 2924
     at JetBrains.Rider.Backend.Features.ProjectModel.RiderSolutionWatcher.<>c__DisplayClass4_0.<.ctor>b__1(Lifetime solutionLifetime, KeyValuePair`2 data) in RiderSolutionWatcher.il:line IL_0074 mvid 2924
     at JetBrains.Collections.Viewable.ReactiveEx.<>c__DisplayClass12_0`2.<View>b__0(Lifetime lf, K k, V v) in ReactiveEx.il:line IL_0000 mvid 2A6A
     at JetBrains.Collections.Viewable.ReactiveEx.<>c__DisplayClass18_0`2.<View>b__0(AddRemove kind, K key, V value) in ReactiveEx.il:line IL_0000 mvid 2A6A
     at JetBrains.Collections.Viewable.ReactiveEx.<>c__DisplayClass15_0`2.<AdviseAddRemove>b__0(MapEvent`2 e) in ReactiveEx.il:line IL_0000 mvid 2A6A
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value) in Fire.il:line IL_0028 mvid 2A6A

**Comment by Garethp** [comment]
I'll be trying to push out an update for `2025.1` this weekend

**Comment by Garethp** [comment]
Looks like the Jetbrains automatic system liked me today! 2024.1.4 has been published and it looks like it's already available for Rider 2025.1
